#!/bin/bash -l
#SBATCH --verbose
#SBATCH --partition=amdq
#SBATCH --nodes 3
#SBATCH --job-name=lmax140
#SBATCH --output=/gpfs/hmurali/string_bootstrap/SUGRABootstrap3/L140_2.out
#SBATCH --error=/gpfs/hmurali/string_bootstrap/SUGRABootstrap3/L140_2.err
#SBATCH --mem 160192
#SBATCH --time 24:00:00

mpirun -v --oversubscribe -np 192 sdpb -s /gpfs/hmurali/string_bootstrap/primalTruncObjnp250ImTonly2_140_31_100 --noFinalCheckpoint --checkpointInterval 10000  --precision 1000 --procsPerNode 64 --maxRuntime 1072800 --maxIterations 100000 --initialMatrixScalePrimal 1e30 --initialMatrixScaleDual 1e30 --dualityGapThreshold 1e-12 --maxComplementarity 1e100 >> /gpfs/hmurali/string_bootstrap/primalTruncObjnp250ImTonly2_140_31_100.log
