#!/bin/bash -l
#SBATCH --verbose
#SBATCH --partition=amddebugq
#SBATCH --nodes 1
#SBATCH --job-name=lmax6
#SBATCH --output=/gpfs/hmurali/string_bootstrap/SUGRABootstrap3/gen_num_integrals_finalopt3_np250_massless2.out
#SBATCH --error=/gpfs/hmurali/string_bootstrap/SUGRABootstrap3/gen_num_integrals_finalopt3_np250_massless2.err
#SBATCH --mem 160192
#SBATCH --time 1:00:00

mpirun -v --oversubscribe -np 64 sdpb -s ./primalTruncObjnp250_6_31_100 --noFinalCheckpoint --checkpointInterval 2000  --precision 1000 --procsPerNode 64  --maxRuntime 1072800 --maxIterations 100000 --initialMatrixScalePrimal 1e30 --initialMatrixScaleDual 1e30 --dualityGapThreshold 1e-12 --maxComplementarity 1e100 >> primalTruncObjnp250_6_31_100.log
